# 공통 설정
spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/RealWorldApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 500
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

---

# local 프로파일 설정
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

---

# test 프로파일 설정
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never